name: Build and Test

on:
  release:
    types: [ created ]

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    env:
      OS: "linux, windows"
      ARCH: "amd64, arm64"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Install xcaddy
        run: |
          sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-xcaddy-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-xcaddy.list
          sudo apt update -y
          sudo apt install -y xcaddy

      - name: Build static releases
        run: |
          for os in $(echo $OS | tr ',' ' '); do
            for arch in $(echo $ARCH | tr ',' ' '); do
              GOOS=${os} GOARCH=${arch} CGO_ENABLED=1 xcaddy build --output caddy-${os}-${arch} --with github.com/quix-labs/caddy-image-processor=.
            done
          done

      - name: Upload Release Assets
        run: |
          for os in $(echo $OS | tr ',' ' '); do
            for arch in $(echo $ARCH | tr ',' ' '); do
              echo "Uploading caddy-${os}-${arch}..."
              curl \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/octet-stream" \
                --data-binary @caddy-${os}-${arch} \
                -X POST "${{ github.event.release.upload_url }}/assets?name=caddy-${os}-${arch}"
            done
          done
#
#      - name: Upload Release Asset (${{ matrix.os }}/${{ matrix.arch }})
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: ./caddy-${{ matrix.os }}-${{ matrix.arch }}
#          asset_name: caddy-${{ matrix.os }}-${{ matrix.arch }}
#          asset_content_type: application/octet-stream