name: Build Static Releases

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build static releases
    runs-on: ubuntu-latest
    env:
      CADDY_VERSIONS: "v2.1.0,v2.2.3,v2.3.0,v2.4.6,v2.5.2,v2.6.4,v2.7.6"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Install xcaddy
        run: |
          sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-xcaddy-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-xcaddy.list
          sudo apt update -y
          sudo apt install -y xcaddy

      - name: Install libvips and libvips-dev
        run: |
          sudo apt-get install -y libvips libvips-dev


      - name: Build static releases
        run: |
          for version in $(echo $CADDY_VERSIONS | tr ',' ' '); do
            CGO_ENABLED=1 xcaddy build ${version} --output caddy-${version} --with github.com/quix-labs/caddy-image-processor=.
          done

      - name: Upload Release Assets
        run: |
          for version in $(echo $CADDY_VERSIONS | tr ',' ' '); do
            echo "Uploading caddy-${version}..."
            curl \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @caddy-${version} \
              -X POST "${{ github.event.release.upload_url }}/assets?name=caddy-${version}"
          done
#
#      - name: Upload Release Asset (${{ matrix.os }}/${{ matrix.arch }})
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: ./caddy-${{ matrix.os }}-${{ matrix.arch }}
#          asset_name: caddy-${{ matrix.os }}-${{ matrix.arch }}
#          asset_content_type: application/octet-stream